from __future__ import annotations

from thematrix.schemas import AuthMode, ProviderKind, ProviderProfile


def provider_catalog() -> list[ProviderProfile]:
    return [
        ProviderProfile(
            provider_id="openrouter",
            display_name="OpenRouter",
            kind=ProviderKind.CLOUD,
            auth_modes=[AuthMode.API_KEY, AuthMode.OAUTH],
            suggested_models=[
                "openai/gpt-5-mini",
                "anthropic/claude-sonnet-4.5",
                "google/gemini-2.5-pro",
            ],
            supports_model_selection=True,
            supports_provider_routing=True,
            supports_structured_output=True,
            data_boundary="cloud: requests pass through OpenRouter to the selected model provider",
            setup_hint="Choose OpenRouter if you want one account for many cloud models.",
        ),
        ProviderProfile(
            provider_id="openai",
            display_name="OpenAI",
            kind=ProviderKind.CLOUD,
            auth_modes=[AuthMode.API_KEY],
            suggested_models=["gpt-5-mini", "gpt-5.1", "gpt-4.1"],
            supports_model_selection=True,
            supports_tools=True,
            supports_structured_output=True,
            supports_prompt_cache=True,
            data_boundary="cloud: requests are sent to OpenAI",
            setup_hint="Use an OpenAI API key.",
        ),
        ProviderProfile(
            provider_id="anthropic",
            display_name="Anthropic",
            kind=ProviderKind.CLOUD,
            auth_modes=[AuthMode.API_KEY],
            suggested_models=["claude-sonnet-4.5", "claude-opus-4.1"],
            supports_model_selection=True,
            supports_structured_output=True,
            data_boundary="cloud: requests are sent to Anthropic",
            setup_hint="Use an Anthropic API key.",
        ),
        ProviderProfile(
            provider_id="gemini",
            display_name="Gemini",
            kind=ProviderKind.CLOUD,
            auth_modes=[AuthMode.API_KEY, AuthMode.OAUTH],
            suggested_models=["gemini-2.5-pro", "gemini-2.5-flash"],
            supports_model_selection=True,
            supports_structured_output=True,
            data_boundary="cloud: requests are sent to Google Gemini",
            setup_hint="Use a Gemini API key or OAuth where supported.",
        ),
        ProviderProfile(
            provider_id="mistral",
            display_name="Mistral",
            kind=ProviderKind.CLOUD,
            auth_modes=[AuthMode.API_KEY],
            suggested_models=["mistral-large-latest", "codestral-latest"],
            supports_model_selection=True,
            data_boundary="cloud: requests are sent to Mistral",
            setup_hint="Use a Mistral API key.",
        ),
        ProviderProfile(
            provider_id="ollama",
            display_name="Ollama",
            kind=ProviderKind.LOCAL,
            auth_modes=[AuthMode.NONE],
            suggested_models=["llama3.2", "qwen2.5-coder", "mistral"],
            supports_model_selection=True,
            data_boundary="local: requests stay on this PC if Ollama is bound to localhost",
            setup_hint="Install Ollama separately and choose a local model.",
        ),
        ProviderProfile(
            provider_id="lmstudio",
            display_name="LM Studio",
            kind=ProviderKind.LOCAL,
            auth_modes=[AuthMode.NONE],
            suggested_models=["local-model"],
            supports_model_selection=True,
            data_boundary="local: requests stay on this PC if LM Studio is bound to localhost",
            setup_hint="Run the LM Studio local server and choose a downloaded model.",
        ),
        ProviderProfile(
            provider_id="custom-openai-compatible",
            display_name="Custom OpenAI-compatible endpoint",
            kind=ProviderKind.CLOUD,
            auth_modes=[AuthMode.API_KEY, AuthMode.LOCAL_TOKEN, AuthMode.NONE],
            suggested_models=["custom-model"],
            supports_model_selection=True,
            data_boundary="custom: depends on the endpoint configured by the user",
            setup_hint="Use this for compatible local or cloud model servers.",
        ),
    ]
